server:
  port: 8081
spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/lagou?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MySQL
    show-sql: true
    #避免将驼峰命名转换为下划线命名
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: lagou-service-code      
